name: Verdict
version: 0.0.1-alpha
main: dev.strwbry.verdict.Verdict
description: 'Modern ticketing and moderation plugin, using the new dialog UI'
authors: [Strwbry, QarthO]
website: https://github.com/StrwbryDev/Verdict
api-version: '1.21.5'
loader: dev.strwbry.verdict.utility.VerdictLoader
