name: EventHorizon
version: 1.0.0-alpha
main: dev.strwbry.eventhorizon.EventHorizon
description: 'A dynamic game mode that introduces configurable random server-wide events to enhance player engagement and replayability'
authors: [Strwbry, xTri]
contributors: [QarthO]
website: https://github.com/StrwbryDev/EventHorizon
api-version: '1.21.4'
dependencies:
  server:
    FastAsyncWorldEdit:
      required: false
    PlaceholderAPI:
      required: false